<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\VideoFetch.Domain\VideoFetch.Domain.csproj" />
    <ProjectReference Include="..\VideoFetch.Application\VideoFetch.Application.csproj" />
    <ProjectReference Include="..\VideoFetch.Infrastructure\VideoFetch.Infrastructure.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

</Project>
